### ISSUE TITLE
Why is timeout built in?

### ISSUE THREAD

**Issue by ajoslin** [hanford/async-function#1]
Looks cool, but just wondering why setTimeout is built in to this. If you want things to always run next tick, promises already do that natively anyway. Just seems like it could cause an unexpected side effect. 

Probably would be better to only set `loading` to true after X ms, instead of delaying the running of the promise.

**Comment by hanford** [comment]
interesting, the setTimout was originally to prevent the promise from resolving "too fast" .. i/e if I have a button that changes to a spinner once loading, it'd be jarring for it to immediately switch back if the promise resolves within > 100ms

However you're right, if the user doesn't supply a `delayMs` value, I probably don't need to wrap the function in a setTimeout.

I'll update the code in a few!

**Comment by hanford** [comment]
ah, didn't realize I had committed the default of 1 second.

**Comment by ajoslin** [comment]
Winning, thanks jack
